
services:

  users-db:
    image: postgres:latest
    container_name: users-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: srvadmin
      POSTGRES_DB: users-db
    ports:
      - "54321:5432"  # Внешний порт можно изменить для каждого контейнера, чтобы избежать конфликтов
    volumes:
      - /home/srvadmin/users-db:/var/lib/postgresql/data

  memorization:
    image: postgres:latest
    container_name: memorization
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: srvadmin
      POSTGRES_DB: memorization
    ports:
      - "54322:5432"  # Внешний порт можно изменить для каждого контейнера, чтобы избежать конфликтов
    volumes:
      - /home/srvadmin/memorization:/var/lib/postgresql/data



